name: Sync Derksen to Shopify
on:
  schedule:
    - cron: "0 3 * * 2-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
      - run: php sync-derksen-to-shopify.php
